# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.srcs/sources_1/ip/c2c_mgt_3p125g/c2c_mgt_3p125g.xci
# IP: The module: 'c2c_mgt_3p125g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/c2c_mgt_3p125g/c2c_mgt_3p125g.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_mgt_3p125g'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/c2c_mgt_3p125g/c2c_mgt_3p125g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_mgt_3p125g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.srcs/sources_1/ip/c2c_mgt_3p125g/c2c_mgt_3p125g.xci
# IP: The module: 'c2c_mgt_3p125g' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/c2c_mgt_3p125g/c2c_mgt_3p125g.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_mgt_3p125g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/c2c_mgt_3p125g/c2c_mgt_3p125g_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c2c_mgt_3p125g'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
