# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/7015_primary.xdc

# XDC: new/debug.xdc

# XDC: new/c2c_mgt.xdc

# IP: ip/ipmc_ila/ipmc_ila.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ipmc_ila || ORIG_REF_NAME==ipmc_ila} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0_2/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ethernet_0_0_2/design_1_axi_ethernet_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_0} -quiet] -quiet

# Block Designs: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/bd_929b.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b || ORIG_REF_NAME==bd_929b} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_0/bd_929b_eth_buf_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b_eth_buf_0 || ORIG_REF_NAME==bd_929b_eth_buf_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_1/bd_929b_mac_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b_mac_0 || ORIG_REF_NAME==bd_929b_mac_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_2/bd_929b_c_shift_ram_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b_c_shift_ram_0_0 || ORIG_REF_NAME==bd_929b_c_shift_ram_0_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_3/bd_929b_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b_c_counter_binary_0_0 || ORIG_REF_NAME==bd_929b_c_counter_binary_0_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_4/bd_929b_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b_xlconstant_0_0 || ORIG_REF_NAME==bd_929b_xlconstant_0_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_5/bd_929b_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_929b_util_vector_logic_0_0 || ORIG_REF_NAME==bd_929b_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_ethernet_0_dma_0_2/design_1_axi_ethernet_0_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_dma_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_0_2/design_1_axi_mem_intercon_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_0 || ORIG_REF_NAME==design_1_axi_mem_intercon_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_0_2/design_1_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_0 || ORIG_REF_NAME==design_1_xbar_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_processing_system7_0_0_3/design_1_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconstant_0_0_3/design_1_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconstant_0_0 || ORIG_REF_NAME==design_1_xlconstant_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0_3/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ps7_0_axi_periph_0_3/design_1_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_1_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_1_3/design_1_xbar_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_1 || ORIG_REF_NAME==design_1_xbar_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlconcat_0_0_3/design_1_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlconcat_0_0 || ORIG_REF_NAME==design_1_xlconcat_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_1_1/design_1_proc_sys_reset_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_1 || ORIG_REF_NAME==design_1_proc_sys_reset_1_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debug_bridge_0_0_3/design_1_debug_bridge_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debug_bridge_0_0 || ORIG_REF_NAME==design_1_debug_bridge_0_0} -quiet] -quiet

# Block Designs: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/bd_c443.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443 || ORIG_REF_NAME==bd_c443} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_0/bd_c443_axi_jtag_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_axi_jtag_0 || ORIG_REF_NAME==bd_c443_axi_jtag_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_1/bd_c443_bsip_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_bsip_0 || ORIG_REF_NAME==bd_c443_bsip_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_2/bd_c443_bs_switch_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_c443_bs_switch_1_0 || ORIG_REF_NAME==bd_c443_bs_switch_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debug_bridge_1_0_2/design_1_debug_bridge_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debug_bridge_1_0 || ORIG_REF_NAME==design_1_debug_bridge_1_0} -quiet] -quiet

# Block Designs: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/bd_0412.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0412 || ORIG_REF_NAME==bd_0412} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/ip/ip_0/bd_0412_xsdbm_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0412_xsdbm_0 || ORIG_REF_NAME==bd_0412_xsdbm_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/ip/ip_1/bd_0412_lut_buffer_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_0412_lut_buffer_0 || ORIG_REF_NAME==bd_0412_lut_buffer_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_0_0_2/design_1_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_1_0_2/design_1_axi_iic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_1_0 || ORIG_REF_NAME==design_1_axi_iic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_2_0_3/design_1_axi_iic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_2_0 || ORIG_REF_NAME==design_1_axi_iic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_3_0_3/design_1_axi_iic_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_3_0 || ORIG_REF_NAME==design_1_axi_iic_3_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_iic_4_0_2/design_1_axi_iic_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_iic_4_0 || ORIG_REF_NAME==design_1_axi_iic_4_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_blk_mem_gen_0_0_3/design_1_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_blk_mem_gen_0_0 || ORIG_REF_NAME==design_1_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_0_3/design_1_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axisafety_2_0_2/design_1_axisafety_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axisafety_2_0 || ORIG_REF_NAME==design_1_axisafety_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axisafety_1_0_3/design_1_axisafety_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axisafety_1_0 || ORIG_REF_NAME==design_1_axisafety_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_jtag_1_0_2/design_1_axi_jtag_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_jtag_1_0 || ORIG_REF_NAME==design_1_axi_jtag_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_jtag_0_0_2/design_1_axi_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_jtag_0_0 || ORIG_REF_NAME==design_1_axi_jtag_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ila_0_0_3/design_1_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_chip2chip_1_0_2/design_1_axi_chip2chip_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_1_0 || ORIG_REF_NAME==design_1_axi_chip2chip_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_chip2chip_0_0_3/design_1_axi_chip2chip_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_0_0 || ORIG_REF_NAME==design_1_axi_chip2chip_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_0_0_3/design_1_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_system_ila_0_0_3/design_1_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_system_ila_0_0 || ORIG_REF_NAME==design_1_system_ila_0_0} -quiet] -quiet

# Block Designs: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/bd_f60c.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c || ORIG_REF_NAME==bd_f60c} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/bd_f60c_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_1/bd_f60c_g_inst_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_g_inst_0 || ORIG_REF_NAME==bd_f60c_g_inst_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_2/bd_f60c_slot_0_aw_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_aw_0 || ORIG_REF_NAME==bd_f60c_slot_0_aw_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_3/bd_f60c_slot_0_w_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_w_0 || ORIG_REF_NAME==bd_f60c_slot_0_w_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_4/bd_f60c_slot_0_b_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_b_0 || ORIG_REF_NAME==bd_f60c_slot_0_b_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_5/bd_f60c_slot_0_ar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_ar_0 || ORIG_REF_NAME==bd_f60c_slot_0_ar_0} -quiet] -quiet

# IP: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_6/bd_f60c_slot_0_r_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_f60c_slot_0_r_0 || ORIG_REF_NAME==bd_f60c_slot_0_r_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pok_alarm_0_0_3/design_1_pok_alarm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pok_alarm_0_0 || ORIG_REF_NAME==design_1_pok_alarm_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_0_1_3/design_1_axi_bram_ctrl_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_0_1 || ORIG_REF_NAME==design_1_axi_bram_ctrl_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_gpio_1_0_2/design_1_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_bram_ctrl_1_0_2/design_1_axi_bram_ctrl_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_bram_ctrl_1_0 || ORIG_REF_NAME==design_1_axi_bram_ctrl_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2c_switch_dual_0_0_3/design_1_i2c_switch_dual_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2c_switch_dual_0_0 || ORIG_REF_NAME==design_1_i2c_switch_dual_0_0} -quiet] -quiet

# IP: ip/ipmc_ila/ipmc_ila.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ipmc_ila || ORIG_REF_NAME==ipmc_ila} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reg_bank_0_0_3/design_1_reg_bank_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reg_bank_0_0 || ORIG_REF_NAME==design_1_reg_bank_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xadc_wiz_0_0_2/design_1_xadc_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2cSlave_0_0_3/design_1_i2cSlave_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2cSlave_0_0 || ORIG_REF_NAME==design_1_i2cSlave_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_i2cSlave_1_0_2/design_1_i2cSlave_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_i2cSlave_1_0 || ORIG_REF_NAME==design_1_i2cSlave_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0_2/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_mem_intercon_1_1/design_1_axi_mem_intercon_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_mem_intercon_1 || ORIG_REF_NAME==design_1_axi_mem_intercon_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xbar_2_2/design_1_xbar_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xbar_2 || ORIG_REF_NAME==design_1_xbar_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_data_fifo_0_0_2/design_1_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_data_fifo_0_0 || ORIG_REF_NAME==design_1_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_jtag_0_0/design_1_axis_jtag_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_jtag_0_0 || ORIG_REF_NAME==design_1_axis_jtag_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_0/design_1_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_0 || ORIG_REF_NAME==design_1_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_1/design_1_util_vector_logic_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_1 || ORIG_REF_NAME==design_1_util_vector_logic_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_2/design_1_util_vector_logic_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_2 || ORIG_REF_NAME==design_1_util_vector_logic_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_0_3/design_1_util_vector_logic_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_0_3 || ORIG_REF_NAME==design_1_util_vector_logic_0_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_1_0/design_1_util_vector_logic_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_1_0 || ORIG_REF_NAME==design_1_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_util_vector_logic_2_0/design_1_util_vector_logic_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_util_vector_logic_2_0 || ORIG_REF_NAME==design_1_util_vector_logic_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_0_3/design_1_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_0_3/design_1_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_1_3/design_1_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_1_3/design_1_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_2_3/design_1_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_2_3/design_1_auto_cc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_0_3/design_1_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_0 || ORIG_REF_NAME==design_1_auto_pc_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_0_0_3/design_1_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_0_0 || ORIG_REF_NAME==design_1_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_1_0_3/design_1_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_1_0 || ORIG_REF_NAME==design_1_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_tier2_xbar_2_0_3/design_1_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_tier2_xbar_2_0 || ORIG_REF_NAME==design_1_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_regslice_0_3/design_1_s00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_0 || ORIG_REF_NAME==design_1_s00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_s00_data_fifo_0_3/design_1_s00_data_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_15_2/design_1_auto_pc_15.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_15 || ORIG_REF_NAME==design_1_auto_pc_15} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m00_regslice_0_3/design_1_m00_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_1_3/design_1_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_1 || ORIG_REF_NAME==design_1_auto_pc_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m01_regslice_0_3/design_1_m01_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_0 || ORIG_REF_NAME==design_1_m01_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_2_3/design_1_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_2 || ORIG_REF_NAME==design_1_auto_pc_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m02_regslice_0_3/design_1_m02_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m02_regslice_0 || ORIG_REF_NAME==design_1_m02_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_3_3/design_1_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_3 || ORIG_REF_NAME==design_1_auto_pc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_m03_regslice_0_3/design_1_m03_regslice_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_m03_regslice_0 || ORIG_REF_NAME==design_1_m03_regslice_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_3_3/design_1_auto_cc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_4_3/design_1_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_4 || ORIG_REF_NAME==design_1_auto_pc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_cc_4_3/design_1_auto_cc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_5_3/design_1_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_5 || ORIG_REF_NAME==design_1_auto_pc_5} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_6_3/design_1_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_6 || ORIG_REF_NAME==design_1_auto_pc_6} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_7_3/design_1_auto_pc_7.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_7 || ORIG_REF_NAME==design_1_auto_pc_7} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_8_3/design_1_auto_pc_8.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_8 || ORIG_REF_NAME==design_1_auto_pc_8} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_9_3/design_1_auto_pc_9.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_9 || ORIG_REF_NAME==design_1_auto_pc_9} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_10_3/design_1_auto_pc_10.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_10 || ORIG_REF_NAME==design_1_auto_pc_10} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_11_3/design_1_auto_pc_11.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_11 || ORIG_REF_NAME==design_1_auto_pc_11} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_12_3/design_1_auto_pc_12.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_12 || ORIG_REF_NAME==design_1_auto_pc_12} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_13_3/design_1_auto_pc_13.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_13 || ORIG_REF_NAME==design_1_auto_pc_13} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_14_2/design_1_auto_pc_14.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_14 || ORIG_REF_NAME==design_1_auto_pc_14} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_us_3_2/design_1_auto_us_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] -quiet

# IP: bd/design_1/ip/design_1_auto_pc_16_2/design_1_auto_pc_16.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_auto_pc_16 || ORIG_REF_NAME==design_1_auto_pc_16} -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/ipmc_ila/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ipmc_ila || ORIG_REF_NAME==ipmc_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/ipmc_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ipmc_ila || ORIG_REF_NAME==ipmc_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/ipmc_ila/ipmc_ila_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0_1/design_1_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_0_1/design_1_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_0/bd_929b_eth_buf_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_929b_eth_buf_0 || ORIG_REF_NAME==bd_929b_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_0/synth/bd_929b_eth_buf_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_929b_eth_buf_0 || ORIG_REF_NAME==bd_929b_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_1/synth/bd_929b_mac_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_929b_mac_0 || ORIG_REF_NAME==bd_929b_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_1/synth/bd_929b_mac_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_929b_mac_0 || ORIG_REF_NAME==bd_929b_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_1/synth/bd_929b_mac_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/ip/ip_1/synth/bd_929b_mac_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_929b_mac_0 || ORIG_REF_NAME==bd_929b_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/bd_0/bd_929b_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/design_1_axi_ethernet_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/synth/design_1_axi_ethernet_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_0_1/synth/design_1_axi_ethernet_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_dma_0_1/design_1_axi_ethernet_0_dma_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_ethernet_0_dma_0_1/design_1_axi_ethernet_0_dma_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_ethernet_0_dma_0 || ORIG_REF_NAME==design_1_axi_ethernet_0_dma_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_processing_system7_0_0_1/design_1_processing_system7_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_processing_system7_0_0 || ORIG_REF_NAME==design_1_processing_system7_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0_1/design_1_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_0_0_1/design_1_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_1_1/design_1_proc_sys_reset_1_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_1 || ORIG_REF_NAME==design_1_proc_sys_reset_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_proc_sys_reset_1_1_1/design_1_proc_sys_reset_1_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_1 || ORIG_REF_NAME==design_1_proc_sys_reset_1_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_0/constraints/axi_jtag.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c443_axi_jtag_0 || ORIG_REF_NAME==bd_c443_axi_jtag_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_0/bd_c443_axi_jtag_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_1/constraints/bsip.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c443_bsip_0 || ORIG_REF_NAME==bd_c443_bsip_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_1/bd_c443_bsip_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_2/constraints/bs_switch.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_c443_bs_switch_1_0 || ORIG_REF_NAME==bd_c443_bs_switch_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/ip/ip_2/bd_c443_bs_switch_1_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/bd_0/bd_c443_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_0_0_1/design_1_debug_bridge_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/ip/ip_0/constraints/xsdbm_cc_early.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0412_xsdbm_0 || ORIG_REF_NAME==bd_0412_xsdbm_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/ip/ip_0/constraints/xsdbm_cc_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0412_xsdbm_0 || ORIG_REF_NAME==bd_0412_xsdbm_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/ip/ip_0/constraints/xsdbm_gc_late.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0412_xsdbm_0 || ORIG_REF_NAME==bd_0412_xsdbm_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/ip/ip_0/bd_0412_xsdbm_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/bd_0/bd_0412_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_debug_bridge_1_0_1/design_1_debug_bridge_1_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0_1/design_1_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_iic_0_0 || ORIG_REF_NAME==design_1_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_0_0_1/design_1_axi_iic_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_1_0_1/design_1_axi_iic_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_iic_1_0 || ORIG_REF_NAME==design_1_axi_iic_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_1_0_1/design_1_axi_iic_1_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_2_0_1/design_1_axi_iic_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_iic_2_0 || ORIG_REF_NAME==design_1_axi_iic_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_2_0_1/design_1_axi_iic_2_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_3_0_1/design_1_axi_iic_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_iic_3_0 || ORIG_REF_NAME==design_1_axi_iic_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_3_0_1/design_1_axi_iic_3_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_4_0_1/design_1_axi_iic_4_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_iic_4_0 || ORIG_REF_NAME==design_1_axi_iic_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_iic_4_0_1/design_1_axi_iic_4_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_blk_mem_gen_0_0_1/design_1_blk_mem_gen_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_ila_0_0_1/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_ila_0_0_1/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_ila_0_0 || ORIG_REF_NAME==design_1_ila_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_ila_0_0_1/design_1_ila_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_chip2chip_1_0_1/design_1_axi_chip2chip_1_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_1_0 || ORIG_REF_NAME==design_1_axi_chip2chip_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_chip2chip_1_0_1/design_1_axi_chip2chip_1_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_1_0 || ORIG_REF_NAME==design_1_axi_chip2chip_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_chip2chip_0_0_1/design_1_axi_chip2chip_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_0_0 || ORIG_REF_NAME==design_1_axi_chip2chip_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_chip2chip_0_0_1/design_1_axi_chip2chip_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_chip2chip_0_0 || ORIG_REF_NAME==design_1_axi_chip2chip_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_0_0_1/design_1_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_0_0 || ORIG_REF_NAME==design_1_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_f60c_ila_lib_0 || ORIG_REF_NAME==bd_f60c_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/ip/ip_0/bd_f60c_ila_lib_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_system_ila_0_0_1/bd_0/bd_f60c_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0_1/design_1_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0_1/design_1_axi_gpio_1_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_1_0_1/design_1_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_gpio_1_0 || ORIG_REF_NAME==design_1_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/ipmc_ila/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ipmc_ila || ORIG_REF_NAME==ipmc_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/ipmc_ila/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ipmc_ila || ORIG_REF_NAME==ipmc_ila} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/ip/ipmc_ila/ipmc_ila_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_xadc_wiz_0_0_1/design_1_xadc_wiz_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_xadc_wiz_0_0 || ORIG_REF_NAME==design_1_xadc_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0_1/design_1_axi_dma_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_axi_dma_0_0_1/design_1_axi_dma_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_0 || ORIG_REF_NAME==design_1_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_0_1/design_1_auto_us_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_0 || ORIG_REF_NAME==design_1_auto_cc_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_0_1/design_1_auto_cc_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_1 || ORIG_REF_NAME==design_1_auto_us_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_1_1/design_1_auto_us_1_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1_1/design_1_auto_cc_1_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_1 || ORIG_REF_NAME==design_1_auto_cc_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_1_1/design_1_auto_cc_1_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_2 || ORIG_REF_NAME==design_1_auto_us_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_2_1/design_1_auto_us_2_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_2_1/design_1_auto_cc_2_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_2 || ORIG_REF_NAME==design_1_auto_cc_2} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_2_1/design_1_auto_cc_2_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_0_1/design_1_auto_pc_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_s00_regslice_0_1/design_1_s00_regslice_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_regslice_0 || ORIG_REF_NAME==design_1_s00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_s00_data_fifo_0_1/design_1_s00_data_fifo_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_s00_data_fifo_0 || ORIG_REF_NAME==design_1_s00_data_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_s00_data_fifo_0_1/design_1_s00_data_fifo_0_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_15_1/design_1_auto_pc_15_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_m00_regslice_0_1/design_1_m00_regslice_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_m00_regslice_0 || ORIG_REF_NAME==design_1_m00_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_1_1/design_1_auto_pc_1_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_m01_regslice_0_1/design_1_m01_regslice_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_m01_regslice_0 || ORIG_REF_NAME==design_1_m01_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_2_1/design_1_auto_pc_2_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_m02_regslice_0_1/design_1_m02_regslice_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_m02_regslice_0 || ORIG_REF_NAME==design_1_m02_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_3_1/design_1_auto_pc_3_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_m03_regslice_0_1/design_1_m03_regslice_0_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_m03_regslice_0 || ORIG_REF_NAME==design_1_m03_regslice_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_3_1/design_1_auto_cc_3_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_3 || ORIG_REF_NAME==design_1_auto_cc_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_3_1/design_1_auto_cc_3_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_4_1/design_1_auto_pc_4_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_4_1/design_1_auto_cc_4_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_cc_4 || ORIG_REF_NAME==design_1_auto_cc_4} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_cc_4_1/design_1_auto_cc_4_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_5_1/design_1_auto_pc_5_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_6_1/design_1_auto_pc_6_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_7_1/design_1_auto_pc_7_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_8_1/design_1_auto_pc_8_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_9_1/design_1_auto_pc_9_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_10_1/design_1_auto_pc_10_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_11_1/design_1_auto_pc_11_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_12_1/design_1_auto_pc_12_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_13_1/design_1_auto_pc_13_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_14_1/design_1_auto_pc_14_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3_clocks.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==design_1_auto_us_3 || ORIG_REF_NAME==design_1_auto_us_3} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_us_3_1/design_1_auto_us_3_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/ip/design_1_auto_pc_16_1/design_1_auto_pc_16_ooc.xdc

# XDC: /home/greshilov/vivado/JTAG_DMA/control/apex_control_mgt/apex_control_mgt.gen/sources_1/bd/design_1/design_1_ooc.xdc
